[project]
name = "nightshift"
version = "0.1.0"
description = "A cool application to working with videos and images that you need to process with FFMPEG and WEBP tools"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "python-multipart>=0.0.21",
    "uvicorn>=0.40.0",
]
